### ISSUE TITLE
java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad

### ISSUE THREAD

**Issue by JosephSanjaya** [ShowMeThe/Orca#5]
###
Version: 2.2.1
Android OS: 13

Got this error after load it with this library
```
java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/~~xiBMrYgzeH_ifIsob6T9rA==/com.app.alpha-329tboGLWjxfIt_74wbCpQ==/lib/x86_64/libapp-core-client.so"
	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
	at java.lang.System.loadLibrary(System.java:1661)
	at com.orcc.app.core.CoreClient.<clinit>(CoreClient.kt:7)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1266)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6785)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```
Any solution?

**Comment by ShowMeThe** [comment]
Firstly,check the ndk abiFilters
```
ndk{
   abiFilters 'x86_64'
}
```

**Comment by ShowMeThe** [comment]
Solve this problem in 2.3.6, please check it and give me some reply. Is this problem can be founded again in new release.

**Comment by JosephSanjaya** [comment]
Havent got time to test it out, maybe tomorrow will check it,

Thank you for your responses
